# Generated by Django 2.1.7 on 2019-03-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0003_userfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=512)),
                ('answer', models.CharField(max_length=512)),
            ],
        ),
    ]
