# Generated by Django 2.1.7 on 2019-03-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0006_dictionarymethods_keywords_listmethods_setmethods_tuplemethods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builtinfunction', models.ForeignKey(on_delete='CASCADE', to='sandbox.BuiltInFunction')),
                ('dictionarymethosd', models.ForeignKey(on_delete='CASCADE', to='sandbox.DictionaryMethods')),
                ('keywords', models.ForeignKey(on_delete='CASCADE', to='sandbox.Keywords')),
                ('listmethods', models.ForeignKey(on_delete='CASCADE', to='sandbox.ListMethods')),
                ('setmethods', models.ForeignKey(on_delete='CASCADE', to='sandbox.SetMethods')),
                ('stringmethods', models.ForeignKey(on_delete='CASCADE', to='sandbox.StringMethods')),
                ('tuplemethods', models.ForeignKey(on_delete='CASCADE', to='sandbox.TupleMethods')),
            ],
        ),
    ]
