# Generated by Django 2.1.7 on 2019-03-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0008_auto_20190319_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='lesson',
            field=models.SmallIntegerField(default=1),
        ),
    ]
