# Generated by Django 2.1.7 on 2019-03-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0011_auto_20190320_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='messenger',
            name='message_title',
            field=models.CharField(default='lol', max_length=128),
            preserve_default=False,
        ),
    ]
